services:
  soom:
    build: .
    container_name: soom
    depends_on:
      db:
        condition: service_healthy
      chromadb:
        condition: service_started
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      CHROMADB_HOST: ${CHROMADB_HOST}
      CHROMADB_PORT: ${CHROMADB_PORT}
    ports:
      - "8080:8080"

  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10
    restart: unless-stopped

  chromadb:
      image: chromadb/chroma
      container_name: chromadb
      ports:
        - "8000:8000"
      volumes:
        - ./chroma-data:/data
      restart: unless-stopped

volumes:
  mysql-data:
  chroma-data: